Fixes handling of methods that contain a comment on method definition line
dduugg/yard-sorbet pull request #17
Opened 2021-01-08 17:48 UTC by KaanOzkan

Before when we saw a method that contained a comment on the same line as its method definition the method was deemed unprocessable and was skipped. As a result any signatures or documentation on the method would be replaced by the comment. 

This commit removes an extraneous check that deems the method processable.

2021-01-08 21:44 UTC, dduugg requested changes
Testing this locally, it appears that prior to this change, YARD would set the node's docstring with the inline comment (`rubocop:disable ...`), consistent with default YARD behavior, although the `sig` information would be lost. Now, I'm seeing the sig information incorporated, by the trailing comment is lost (i.e. the docstring is an empty string). I can PR a failing test to your branch to demonstrate this if you like.

I could be convinced to allow the change in behavior (the nearest analogue would be a method with both a preceding and inline comment, in which case YARD appears to discard the latter, while it uses the inline comment as the docstring if there is no preceding comment), but it would be nice if we could maintain existing behavior while incorporating `sig` information. What do you think?

We should also update the CHANGELOG with the bug fix information.

2021-01-08 21:44 UTC, dduugg commented on spec/data/sig_handler.rb.txt
> +  end
We should test the other node types as well (`defs` and `command`). We might want to consider 3.0 `end`less defs as well, but probably better to take 3.0 support to a separate PR.

2021-01-08 21:44 UTC, dduugg commented on spec/yard_sorbet/sig_handler_spec.rb
> +      expect(node.tag(:return).types).to eq(['void'])
Let's have `docstring` expectations as well (see comment on the PR overall).

2021-01-09 01:13 UTC, KaanOzkan commented
Yes. That is correct. My apologies for not mentioning that in the PR description after our month old chat 😃.

I'm actually skeptical of the Yard's behaviour in this case especially since in my experience comments on the same line as a method definition have always been rubocop comments. In that particular case it made sense to me to keep the actual docstring and the sig in our output. 

However, I totally understand that we would want to keep consistent with Yard behaviour. Let me know your preference, I think it would be possible so I can implement that version too. 

I now realize I was biased because my first time encountering this bug the yard comments user have written were replaced with an insignificant Rubocop comment.

2021-01-10 20:57 UTC, dduugg commented
@KaanOzkan got it, thanks for clarifying. I'm ok moving forward with this. Could I trouble you to:

- add a changelog entry
- test the remaining node types
- explicitly test the docstrings (perhaps with a comment that we're testing just to document existing behavior, but might want to incorporate inline comments down the line).

Thanks, as always, for your contributions!

2021-01-12 03:25 UTC, dduugg commented
Latest changes look good, they just needed a test for `command` types and some minor cleanup. I've opened a PR to your branch.

2021-01-12 17:28 UTC, merged